Bridge azure properties to spring starter to authenticate
saragluna/azure-sdk-for-java pull request #5
Opened 2021-07-23 01:56 UTC by moarychan

Fixes Azure/azure-sdk-for-java#21971

Based on the target PR changes, try to use each starter property class and the super `AzureProperties` to construct `TokenCredential` to authenticate.

Changelog;
- Add `MappingCredentialPropertiesProvider.java` bean to mapping each module properties to `MappingCredentialPropertiesProvider` implementation.
- Each module will use `SpringEnvironmentCredentialBuilder` object to build a starter's `TokenCredential` which will be used as a credential option.
- Provider `DefaultStorageQueueClientFactory` to cover the common use-cases, and combine the `QueueClientBuilderCustomizer` bean to allow users to customize the queue client builder. This approach may be applied to build the service client builder for EventHubs and Service Bus.

Welcome to submit comments.

Todolist:
- [x] Cosmos
- [x] Storage Blob
- [x] Storage Queue
- [ ] [WIP] KeyVault
- [ ] EventHubs
- [ ] Service Bus
- [ ] Update and add Unit testcases
- [ ] Test with all related samples
- [ ] Update dev docs

2021-07-26 01:31 UTC, moarychan commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/autoconfigure/unity/identity/AzureDefaultTokenCredentialAutoConfiguration.java
> +@ConditionalOnProperty(name = AzureProperties.PREFIX)
No, I will remove it

2021-08-02 02:17 UTC, saragluna requested changes

2021-08-02 02:17 UTC, saragluna commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/autoconfigure/cosmos/CosmosAutoConfiguration.java
> +    public ClientBuilderCustomizer<CosmosClientBuilder> cosmosClientBuilderCustomizers() {
How about putting this into the builder creation method?

2021-08-02 02:17 UTC, saragluna commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/autoconfigure/cosmos/CosmosClientBuilderConfigurer.java
> +        if (azureKeyCredentialCustomizer != null) {
How about omitting the DefaultSkipCredentialCallback and setting the credential by precedence, first setting the lower precedence and higher precedence.

2021-08-03 02:42 UTC, stliu commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/autoconfigure/cosmos/CosmosAutoConfiguration.java
> +                       .orElse(null);
null?

2021-08-03 02:44 UTC, stliu commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/autoconfigure/cosmos/CosmosAutoConfiguration.java
> +        return null;
we should discuss this design, I'm really not sure if it is the right way to do this

2021-08-03 02:45 UTC, stliu commented on sdk/spring/azure-spring-cloud-autoconfigure/src/main/java/com/azure/spring/autoconfigure/cosmos/CosmosAutoConfiguration.java
> +        return null;
btw, you can use `ObjectProvider` to get rid of this `@Autowired(required=false)`

2021-09-06 01:38 UTC, saragluna commented
Already merged in this PR https://github.com/Azure/azure-sdk-for-java/pull/23787. Closing this one now.

2021-09-06 01:38 UTC, closed without merging